local c = require "colors"

return {
  set = {
    { name = "Comment",      fg = c.gray_l, attr = "italic"      },
    { name = "Identifier",   fg = c.white                        },
    { name = "Constant",     fg = c.pink                         },
    { name = "PreProc",      fg = c.purple                       },
    { name = "Function",     fg = c.yellow                       },
    { name = "Statement",    fg = c.yellow                       },
    { name = "Type",         fg = c.yellow                       },
    { name = "Operator",     fg = c.white,  attr = "bold"        },
    { name = "Special",      fg = c.purple, attr = "bold"        },
    { name = "Underline",    fg = c.purple, attr = "bold"        },
    { name = "Error",        fg = c.red,    attr = "bold,italic" },
    { name = "Todo",         fg = c.orange, attr = "bold,italic" },
    { name = "ColorColumn",  bg = c.gray_d                       },
    { name = "Conceul",      fg = c.gray_d                       },
    { name = "Cursor",       fg = c.black, bg = c.yellow         },
    { name = "CursorColumn", bg = c.gray_d                       },
    { name = "CursorLine",   bg = c.gray_d                       },
    { name = "Directory",    fg = c.yellow                       },
    { name = "Folded",       fg = c.gray_d                       },
    { name = "IncSearch",    bg = c.gray_d                       },
    { name = "Substitute",   bg = c.gray_d                       },
    { name = "LineNr",       fg = c.gray_d                       },
    { name = "CursorLineNr", fg = c.gray_d                       },
    { name = "Normal",       fg = c.white, bg = c.black          },
    { name = "FloatBorder",  fg = c.gray_d                       },
    { name = "FloatTitle",   fg = c.gray_d                       },
    { name = "Pmenu",        fg = c.white, bg = c.gray_d         },
    { name = "PmenuSel",     fg = c.white, bg = c.yellow         },
    { name = "PmenuSbar",    bg = c.blue_d                       },
    { name = "PmenuThumb",   bg = c.gray_l                       },
    { name = "Question",     fg = c.pink                         },
    { name = "QuickFixLine", bg = c.gray_d                       },
    { name = "Search",       bg = c.gray_d                       },
    { name = "SpeacialKey",  bg = c.blue_d                       },
    { name = "SpeacialKey",  bg = c.red                          },
    { name = "SpellBad",     bg = c.red,    attr = "bold,italic" },
    { name = "SpellCap",     bg = c.orange, attr = "italic"      },
    { name = "SpellLocal",   bg = c.red,    attr = "italic"      },
    { name = "SpellRare",    bg = c.orange                       },
    { name = "StatusLine",   fg = c.white,  bg = c.gray_d        },
    { name = "StatusLineNC", fg = c.white                        },
    { name = "TabLine",      fg = c.white,  bg = c.gray_d        },
    { name = "TabLineFill",  fg = c.white,  bg = c.gray_d        },
    { name = "TabLineSel",   fg = c.white,  bg = c.gray_l        },
    { name = "Visual",       fg = c.gray_l, bg = c.gray_d        },
    { name = "VisualNOS",    fg = c.gray_d, bg = c.gray_l        },
    { name = "WarningMsg",   fg = c.orange                       },
    { name = "ErrorMsg",     fg = c.red                          },
    { name = "WildMenu",     fg = c.gray_d, bg = c.yellow        },
    { name = "EndOfBuffer",  fg = c.gray_d                       },
    { name = "WinBar",       bg = c.black                        },
  },
  link = {
    { dst = "NormalFloat", src = "Normal" },
    { dst = "NormalNC",    src = "Normal" },
    { dst = "WinBarNC",    src = "WinBar" },
  }
}
